/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Perfume = IDL.Record({
  'id' : IDL.Nat,
  'heartNotes' : IDL.Text,
  'name' : IDL.Text,
  'longevity' : IDL.Nat,
  'description' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : IDL.Text,
  'baseNotes' : IDL.Text,
  'projection' : IDL.Nat,
  'price' : IDL.Text,
  'isBestSeller' : IDL.Bool,
  'topNotes' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPerfumes' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
  'getPerfumeById' : IDL.Func([IDL.Nat], [IDL.Opt(Perfume)], ['query']),
  'getPerfumesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Perfume)], ['query']),
  'init' : IDL.Func([], [], []),
  'searchPerfumes' : IDL.Func([IDL.Text], [IDL.Vec(Perfume)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Perfume = IDL.Record({
    'id' : IDL.Nat,
    'heartNotes' : IDL.Text,
    'name' : IDL.Text,
    'longevity' : IDL.Nat,
    'description' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : IDL.Text,
    'baseNotes' : IDL.Text,
    'projection' : IDL.Nat,
    'price' : IDL.Text,
    'isBestSeller' : IDL.Bool,
    'topNotes' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPerfumes' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
    'getPerfumeById' : IDL.Func([IDL.Nat], [IDL.Opt(Perfume)], ['query']),
    'getPerfumesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Perfume)],
        ['query'],
      ),
    'init' : IDL.Func([], [], []),
    'searchPerfumes' : IDL.Func([IDL.Text], [IDL.Vec(Perfume)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };